name: CI/CD Pipeline

on:
  push:
    branches: [ balu ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest
      - name: Build Docker image and Run tests
        run: |
          docker compose up --build -d
          docker compose exec app python -m pytest
          docker compose down